global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'prasanna.pailwan35@gmail.com'
  smtp_auth_username: 'prasanna.pailwan35@hmail.com'
  smtp_auth_password: 'kephioyfmcradhip'

route:
  receiver: 'email-alerts'

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'prassanapailwan@gmail.com'
    send_resolved: true
