apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  selector:
    app: django-backend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
