apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - '/etc/prometheus/alerts.yml'

    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/metrics/'
        static_configs:
          - targets: ['192.168.105.5:30001']

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - '{{ .Values.alertmanager.service.nodePort }}'

  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
        - alert: HighStockChange
          expr: stock_daily_percentage_change > 2
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Stock change in percent exceeded 2%"
            description: "Stock has a change in percent which is above 2%."


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30900
  selector:
    app: prometheus
