apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  selector:
    app: django-backend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: prassana1132/my_django_app:apline2
          ports:
            - containerPort: 8000

