apiVersion: v2
name: stock-app
version: 0.1.0
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: database
    version: 0.1.0
    repository: "file://charts/database"
  - name: monitoring
    version: 0.1.0
    repository: "file://charts/monitoring"
