prometheus:
  image: prom/prometheus:latest
  replicas: 1
  config:
    scrape_interval: '15s'
    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['192.168.105.5:30001']
    rule_files:
      - '/etc/prometheus/alerts.yaml'

alertmanager:
  image: prom/alertmanager:latest
  replicas: 1
  config:
    smtp_smarthost: 'smtp.gmail.com:587'
    smtp_from: 'prasanna.pailwan35@gmail.com'
    smtp_auth_username: 'prasanna.pailwan35@gmail.com'
    smtp_auth_password: 'ypugqpwaadpexzbj'
    smtp_require_tls: true
    receivers:
      - name: 'email_notifications'
        email_configs:
          - to: 'prassanapailwan@gmail.com'
            send_resolved: true
    route:
      receiver: 'email_notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

grafana:
  image: grafana/grafana:latest
  admin_password: 'admin'
  replicas: 1
