apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['192.168.105.6:30001']

    rule_files:
      - '/etc/prometheus/alerts.yml'

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - '192.168.105.6:31002'
  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: HighStockChange
            expr: stock_change_in_percent > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Stock change in percent exceeded 2%"
              description: "Stock has a change in percent of which is above 2%."
