scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']  # Replace with your Django app's address and port
    rule_files:
      - "rules.yml"
